services:
  db:
    image: postgres:17
    container_name: db_nxtc
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - JDBC_DATASOURCE_URL=${JDBC_DATASOURCE_URL}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: