services:
  db:
    image: postgres:17
    container_name: db_nxtc
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  angular-app:
    build:
      context: ./nxtc-frontend
      dockerfile: dockerfile
    ports:
      - "4200:80"

  api:
    build:
      context: ./nxtc-api
      dockerfile: dockerfile
    env_file:
      - /.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JDBC_DATASOURCE_URL=${JDBC_DATASOURCE_URL}
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  pgdata: