FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install -g @angular/cli@19
RUN npm install
COPY . .
RUN ng build
FROM nginx:alpine
COPY --from=build /app/dist/nxtc-frontend /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]